name: Deploy workflow

on:
  push:

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # test:
  # uses: ./.github/workflows/test.yml
  deploy:
    # needs: test
    uses: ./.github/workflows/deploy.yml
