name: Test workflow

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup Node 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Run required containers
        run: docker-compose -f docker-compose.test.yml up -d

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Run test
        run: npm run test
